spring:
  config:
    activate:
      on-profile: local
    import: optional:application-secret.properties
  jpa:
    hibernate:
      ddl-auto: create # 실제 서버에서 사용시 모든 데이터가 다 날아가므로 주의
    properties:
      hibernate:
        format_sql: true
    show-sql: true


swagger.version: "v0.1"


