spring:
  config:
    activate:
      on-profile: actuator


# https://techblog.woowahan.com/9232/ 참고
management:
  endpoints:
    web:
      exposure:
        include: health # include specific endpoint
      base-path: /depromeet-actuator # change webBase path
    enabled-by-default: false # endpoint all disable
    jmx:
      exposure:
        exclude: * # exclude all jmx endpoint
  endpoint:
    health:
      enabled: true # enable specific endpoint

