spring:
  config:
    activate:
      on-profile: actuator


# https://techblog.woowahan.com/9232/ 참고
management:
  endpoints:
    web:
      exposure:
        # include specific endpoint
        include: health
        # change webBase path
      base-path: /depromeet-actuator
    jmx:
      exposure:
        exclude: "*"
    # endpoint all disable
    enabled-by-default: false
  endpoint:
    health:
      # enable specific endpoint
      enabled: true

