spring:
  config:
    activate:
      on-profile: local
    import: optional:application-secret.properties
  jpa:
    hibernate:
      ddl-auto: create # 실제 서버에서 사용시 모든 데이터가 다 날아가므로 주의
    defer-datasource-initialization: false
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  sql:
    init:
      mode: never
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 20MB
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      s3:
        bucket: ${AWS_BUCKET}


swagger.version: "v0.1"


