spring:
  config:
    activate:
      on-profile: actuator

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: ${KAKAO_REDIRECT_URL}
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - profile_image
              - email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  access-token-secret: ${ACCESS_TOKEN_SECRET}
  refresh-token-secret: ${REFRESH_TOKEN_SECRET}
  access-token-expiration-time: ${ACCESS_TOKEN_EXP}
  refresh-token-expiration-time: ${REFRESH_TOKEN_EXP}
  issuer: ${ISSUER}